version: "3.1"

services:
  db:
    image: postgres:16
    restart: always
    container_name: postgres-test-db
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: prisma
      POSTGRES_PASSWORD: prisma
      POSTGRES_DB: tests
